#ifndef _INDEX_HTML_GZ_H
#define _INDEX_HTML_GZ_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

extern const unsigned char index_html_gz_start[];
extern const size_t index_html_gz_size;

#endif
